export { default as Artist } from './pages/Artist'
export { default as Download } from './pages/Download'
export { default as Favorite } from './pages/Favorite'
export { default as Genre } from './pages/Genre'
export { default as Main } from './pages/Main'
export { default as Musicvideo } from './pages/Musicvideo'
export { default as Playlist } from './pages/Playlist'
export { default as WeatherPlaylist } from './pages/WeatherPlaylist'
export { default as Popular } from './pages/Popular'
export { default as Musicplayer } from './pages/Musicplayer'
export { default as Loader } from './Loader'

export { default as AlbumCont } from './layout/AlbumCont'
export { default as RankCont } from './layout/RankCont'
export { default as ArtistCont } from './layout/ArtistCont'
export { default as WeatherCont } from './layout/WeatherCont'
export { default as PlayListCont } from './layout/PlayListCont'
export { default as RecentCont } from './layout/RecentCont'

export { default as Details } from './pages/details/Details'
